### ISSUE TITLE
olk recent:today error

### ISSUE THREAD

**Issue by grchen** [xeric/alfred-outlook#9]
[22:08:44.961] Logging Started...
[22:08:50.882] Outlook Search[Script Filter] Queuing argument 'recent:today'
[22:08:51.057] Outlook Search[Script Filter] Script with argv 'recent:today' finished
[22:08:51.059] ERROR: Outlook Search[Script Filter] Code 1: 22:08:50 workflow.py:1689 DEBUG    loading cached data: /Users/grchen/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.xericwei.alfred/__workflow_update_status.cpickle
22:08:50 workflow.py:2269 DEBUG    update_data: {u'available': False}
.
22:08:50 workflow.py:2055 DEBUG    ---------- Outlook Search (0.1.8) ----------
22:08:50 workflow.py:1462 DEBUG    reading settings from /Users/grchen/Library/Application Support/Alfred/Workflow Data/com.xericwei.alfred/settings.json
22:08:50 workflow.py:2339 DEBUG    update check not due
22:08:50 workflow.py:1565 DEBUG    no data stored for `filter`
22:08:50 workflow.py:1579 DEBUG    data `profile` stored as `cpickle`
22:08:50 workflow.py:1594 DEBUG    stored data loaded: /Users/grchen/Library/Application Support/Alfred/Workflow Data/com.xericwei.alfred/profile.cpickle
22:08:50 main.py:73 INFO     configured profile isMain Profile
22:08:50 workflow.py:1579 DEBUG    data `profile` stored as `cpickle`
22:08:50 workflow.py:1594 DEBUG    stored data loaded: /Users/grchen/Library/Application Support/Alfred/Workflow Data/com.xericwei.alfred/profile.cpickle
22:08:50 main.py:79 INFO     /Users/grchen/Library/Group Containers/UBF8T346G9.Office/Outlook/Outlook 15 Profiles/Main Profile/Data/
22:08:50 main.py:98 INFO     query string is: recent:today
22:08:50 main.py:99 INFO     query page is: 0
22:08:50 workflow.py:1565 DEBUG    no data stored for `pagesize`
22:08:50 workflow.py:1565 DEBUG    no data stored for `folder`
22:08:50 main.py:280 INFO     query by subject, content and sender
22:08:50 main.py:281 INFO     []
22:08:50 workflow.py:2074 ERROR    coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "/Users/grchen/iWork/software/alfredbak/Alfred.alfredpreferences/workflows/user.workflow.5B2850D7-FF6F-41F3-A0B5-6A26315945B7/workflow/workflow.py", line 2067, in run
    func(self)
  File "main.py", line 47, in main
    handle(wf, query)
  File "main.py", line 134, in handle
    searchMethod(cur, keywords, offset, calculatedPageSize + 1, folder)
  File "main.py", line 275, in queryRecent
    queryAll(cur, keywords[1:], offset, pageSize, folder, top)
  File "main.py", line 320, in queryAll
    conditions = "(" +  conditions
TypeError: coercing to Unicode: need string or buffer, NoneType found
22:08:50 workflow.py:2097 DEBUG    ---------- finished in 0.029s ----------
[22:08:51.061] Outlook Search[Script Filter] {"items": [{"valid": false, "subtitle": "coercing to Unicode: need string or buffer, NoneType found", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'Outlook Search'"}]}

**Comment by xeric** [comment]
I can reproduce this issue and will look into it ASAP, thanks for reporting it.

**Comment by grchen** [comment]
thanks

**Comment by xeric** [comment]
Issue has been fixed in version 0.1.9.
